### ISSUE TITLE
Improve the NBT Match rule

### ISSUE THREAD

**Issue by Catnies** [PluginBugs/Issues-VanillaCustomizer#3]
### Terms

- [X] I'm using the very latest version of VanillaCustomizer and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-VanillaCustomizer/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/vanillacustomizer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

1.The NBT matching rule can match multiple values, Instead of having to create multiple rules.
I did not find a batch processing method related to NBT in the WIKI and Example file.
```yml
    rules:
      nbt:
        path: "itemsadder.id"
        value: 
         - spiritual_sand
         - abnormal_slab
        type: string`
```
2. NBT for Int can match the size of the value.
This makes it easy to create Rare categories for the same RPG Item, based on a number of values.
```yml
    rules:
      nbt:
        path: "ItemDamage.Value"
        value: 
          - '>=15.5'
          - '<25'
        type: int`
```

### Is your feature request related to a problem?

yes

### Describe alternatives you've considered

.
