### ISSUE TITLE
[FEATURE REQUEST] Ignore rule!

### ISSUE THREAD

**Issue by PSYCHEER** [PluginBugs/Issues-VanillaCustomizer#6]
### Terms

- [X] I'm using the very latest version of VanillaCustomizer and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-VanillaCustomizer/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/vanillacustomizer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

PSYCHEER

### Describe the solution you'd like

![image](https://github.com/PluginBugs/Issues-VanillaCustomizer/assets/42911029/9134ca4c-3172-46ac-823c-cd6fb7df9fe8)
It's basic, just like 
material_wildcard:
- itemsadder_*
ignore: true

everything what will match, will be ignored

### Is your feature request related to a problem?

No

### Describe alternatives you've considered

Haven't any

**Comment by LoneDev6** [comment]
Can you please elaborate what would be the usage of this?
Make some example configuration.

For example:
```yml
  iconic_rare:
    enabled: true
    rules:
      materials:
      - "DRAGON_EGG"
      - "DRAGON_HEAD"
      - "NETHER_STAR"
      is_vanilla_item: true
    changes:
      lore_insert_json:
        index: 1
        lines:
        - '[{"text":"f", "font":"simple_vanilla_enhancer:tags"}]' # Iconic
        - '[{"text":"c", "font":"simple_vanilla_enhancer:tags"}]' # Rare artifact
```
